### PR TITLE
Merge branch 'master' of https://github.com/standardebooks/charlotte-bronte_villette

### PR DESCRIPTION
**Pull request by jennfrye**
As preparation for adding endnotes, I went through and added French language tags to a number of French words/phrases, and also corrected various typos I came across. (31af201 is incorrect and should be deleted, but I could not for the life of me figure out how to remove that one commit—hoping you can just not accept that one?)

### CODE REVIEW

**Comment by acabal** [comment]
This is great work, thanks!

I'm just looking at the first item, chapter-10, and there are some issues that should be addressed in the PR in general before we can merge it in:

- We should not convert from French to emphasis if the phrase isn't actually being spoken with emphasis. For example in `chapter-10.xhtml` you change `fiacre` from French to emphasis, but 1) it's in M-W so it should not be in French italics to begin with and 2) it's not being spoken with emphasis so it should not be `<em>`. Rather, italics should be removed entirely.  See https://standardebooks.org/manual/1.7.0/single-page#8.2.9
- Same with `gourmande` right below it. This is the modern English word `gourmand` but before the spelling changed, so we should not italicize it, but rather remove the `e` as an editorial commit.
- `pensionnat` is in M-W so it should not be italicized.

And so on. Since this PR is so large I only looked at the first file for now, but I assume this is repeated throughout. Can you review the PR to correct these issues across the board? Thanks!

**Comment by jennfrye** [comment]
> This is great work, thanks!
> 
> I'm just looking at the first item, chapter-10, and there are some issues that should be addressed in the PR in general before we can merge it in:
> 
> * We should not convert from French to emphasis if the phrase isn't actually being spoken with emphasis. For example in `chapter-10.xhtml` you change `fiacre` from French to emphasis, but 1) it's in M-W so it should not be in French italics to begin with and 2) it's not being spoken with emphasis so it should not be `<em>`. Rather, italics should be removed entirely.  See https://standardebooks.org/manual/1.7.0/single-page#8.2.9
> * Same with `gourmande` right below it. This is the modern English word `gourmand` but before the spelling changed, so we should not italicize it, but rather remove the `e` as an editorial commit.
> * `pensionnat` is in M-W so it should not be italicized.
> 
> And so on. Since this PR is so large I only looked at the first file for now, but I assume this is repeated throughout. Can you review the PR to correct these issues across the board? Thanks!

Thanks for the feedback! A few things:

* I knew the French tag needed to be removed, but I thought the emphasis needed to be kept because it's emphasized (italicized) in the [source scans](https://archive.org/details/villettenovel00bronuoft/page/92/mode/2up?q=fiacre). Is this correct?
* "gourmande" poses a problem as it's a French word that (looking at a French dictionary) can mean the same thing as its English counterpart. It's my interpretation that Bronte intentionally scatters French words throughout the text to give the novel more of a French (well, technically Belgian) feel, and if this is the case it should probably be preserved. So how do we know if Bronte means to write an English word or a French one? Later in the novel, one character calls another “Petite gourmande!”, currently (and I think correctly) tagged as French, so perhaps that indicates that she did intend the French. M-W gives "gourmaunt" as the Middle English spelling, which makes me think that "gourmande" was probably never a common English spelling of the word (though spelling rules were a bit fast and loose, so who knows). Regardless, this issue definitely pops up in other places; "blasée" and "clairvoyante" come to mind…so let me know how I should handle these. 
* In the case of "pensionnat," I thought tagging and italicizing this was correct because it's only in the unabridged M-W, and not in the basic online search. If this isn't the case, there are a ton of other changes to undo. 

Let me know what you want me to do!

**Comment by acabal** [comment]
`fiacre` isn't italicized for emphasis, it doesn't make much sense for an emphasis to be placed on that word in that context. Rather it's italicized as a loan word, just like we would italicize similar loan words today. The difference is that 150 years ago it was a loan word, but today it's in M-W, so we don't italicize it any more.

Re. `gourmand`, we can remove the `e` and remove italics in the English context. In the French context you can keep it because they're speaking French. You can also modernize `blasé` as that's just English now. `clairvoyante` can actually be left alone (but without italics) as it technically means a female clairvoyant.

I see your point about `pensionnat`, I didn't look closely enough in M-W. So we can accept that. However the point stands for the rest of this PR.

**Comment by jennfrye** [comment]
Thanks for the quick response. Sorry to be difficult but I have a few more questions—I'm probably overthinking things.

Re: "fiacre" and the issue of emphasis, I actually do think that emphasis may be intended—perhaps to emphasize that Madame got her way, or to mock her word choice, or because there's something special about a fiacre that Bronte wanted to draw the reader's attention to—as [later in the novel](https://archive.org/details/villettenovel00bronuoft/page/186/mode/2up?q=fiacre) the source text does not emphasize "fiacre." I thought perhaps just the first usage of the word was emphasized because that was the approach to handling loan words, but "blasée" is [emphasized both times it comes up](https://archive.org/details/villettenovel00bronuoft/page/50/mode/2up?q=blas%C3%A9e) (probably because Lucy is mocking of Ginevra's somewhat melodramatic word choice), "coiffeur" is [not initially emphasized](https://archive.org/details/villettenovel00bronuoft/page/128/mode/2up?q=coiffeur) but [is emphasized later](https://archive.org/details/villettenovel00bronuoft/page/130/mode/2up?q=coiffeurs) (I have no idea why), "rôle" is emphasized the first few times but not the last, "naïveté" is [emphasized](https://archive.org/details/villettenovel00bronuoft/page/188/mode/2up?q=naivete) then [not emphasized](https://archive.org/details/villettenovel00bronuoft/page/220/mode/2up?q=naivete) then [emphasized](https://archive.org/details/villettenovel00bronuoft/page/316/mode/2up?q=naivete), there are plenty of loan words like "pensionnat" and "chaussée" that are never emphasized at all… In short, there seems to be no obvious emphasis patterns. What to do with all of these? 

Re: "gourmande" and the rest, I'm not sure that's a consistent approach. "Gourmande" and "blasée" are also the feminine forms of the French words "gourmand" and "blasé," in the same way that "clairvoyante" is the feminine form of "clairvoyant." (Also true for "nonchalante", "compatriote", and per M-W then kind of "pianiste," though it looks like pianiste may be gender-neutral in actual French.) Then there are other loan words that are spelled the French way but are very close to the English: chiffonnière (chiffonier),  guéridon (gueridon), Empereur (Emperor), crac (crack), Béguines (Beguines), manoir (manor), and duc (duke). This may just scratch the surface as there are a ton of other French words that were already tagged and that I therefore haven't looked at yet, though I noticed some like professeurs (professors) and classe (class), the latter of which appear dozens of times. I'm hesitant to "Anglicize" the text and remove what seems to be an intentional French flavor, given that (with a couple of exceptions) I haven't found other outdated spellings of non-French words. Perhaps I should just the original spelling and tag them as French but without adding any emphasis?

Then there are three words that appear in M-W but seem to be used as French: "garçon" (Paul is clearly saying Lucy is acting like a boy, not like a waiter), "marmot" (I haven't touched this one—but it would make more sense for the children to be referred to being "brats," the French definition, and not as being rodents), and "classes" (I haven't touched this one either—this often, but not always, seems to refer to the French meaning of "classrooms"). I tagged "garçon" but don't know what to do with the others. 

The only other words I incorrectly tagged (going off M-W) were rôle and brava. When I make these and other corrections, can I just create new commits or do I need to undo and correct them?

Sorry for the essay.

**Comment by acabal** [comment]
Don't overthink this. This printing is nearly 150 years old. The concept of authorial intent didn't exist then - that's a modern concept borne of mid-20th-century universities that took the novel from "things people read to pass the time" to "high art form in which every punctuation mark is carefully scrutinized and deconstructed".  

In 1864, typesetters were setting each letter by hand, working off often-barely-readable handwritten manuscripts, and nobody was going to haul the 20-lb lead setting of page 3 from a closet to double check if they italicized that word that one time before. Different typesetters would work on different pages and different editions and literally do their own spellings and punctuation.

A typesetter does some weird thing in some edition, the author dies 2 years later, and next thing you know that weird edition becomes what everyone bases *their* editions on. Then 150 years later, we go from an overworked typesetter deciphering a holograph written in cursive, and making whatever changes he thought sounded better without a second thought, to "the author surely must have meant this comma to have special meaning" and people writing papers about it :)

So having said all that - 

I think the inconsistent italics you note highlight the situation I described. `blasé`, `coiffure`, `rôle`, `naïveté` - all of these are French loan words, and so it stands to reason that they are not *emphasized*, but rather *italicized as loan words* especially given their context in the text. (According to M-W `blasé` only first enters the language a mere 34 years before this book was first published.) It was very common to do this in texts of the time period - I've worked on countless.  So if we're reaching for reasons why things might be italicized, then it's more likely the inconsistencies are just mistakes and our supposition of them being loan words is right.

This particular book does seem to have a lot of valid exceptions for spellings, and that's OK. It makes sense to keep exceptions in dialogue where perhaps people might be seen as speaking with an accent. I think many of the items you listed fall under that. Other items are still in fact English - `manoir` has its own entry in M-W for example. Other items are not words per se - `crac` is just onomatopoeia in context and could very well be spelled with a `k`. But generally we're not super interested in adjusting spelling for anything that `se modernize-spelling` doesn't automatically do.

So I'm not too worried about the spellings, but more so the italics, which, when placed on words we recognize today as English, are more confusing to modern readers than not. 

You don't have to rebase anything, you can just make new commits to adjust things.

**Comment by jennfrye** [comment]
Apologies for the delayed response, life/work is getting busier with the holidays. Thanks so much for sharing that background and context! Interesting stuff, I was entirely unaware. 

I'll go through and remove the italics from the loan words I mentioned and others I come across, and will keep the French but without emphasis. 

Thanks for your patience :)

**Comment by acabal** [comment]
Take your time, I'm also extremely busy through the holidays so I might not have a chance to get to this soon anyway! :)

**Comment by acabal** [comment]
Sorry for the delay. Looks very good now. Thanks, great work!

**Pull request merged**
