### PR TITLE
Added French translations in endnotes

### PR DESCRIPTION
**Pull request by jennfrye**
Translations are from the public domain. 

`se build --check-only` and `se lint` both come back clean except for those errors that I always get no matter how many times I try to upgrade the toolset (with the exception of some endnote formatting choices—I thought it made more sense to mirror the "source" punctuation and use single quotation marks rather than turning them into double quotation marks). 

Edit: I just remembered I forgot to fix another typo I found…wanted to wait until the translations were committed and then I forgot. I'm worried rescinding a pull request, making changes, and re-sending it will be too complicated for me right now—do you mind making this change? The word "nest-ce" in the lines _“Nest-ce pas que c’est beau?”_ and _“Le marmot n’a rien, nest-ce pas?”_ should be "n’est-ce," with an apostrophe (verified with the source scans).

### CODE REVIEW

**Comment by acabal** [comment]
Thanks! We do need to fix all the lint errors before we continue. You can use double quotes in those extracts, since without a parent double quote it's unclear why those are single quoted.

You also need to update the manifest which got out of order, and add annotator semantic inflection. The annotator is whoever did the translations, possibly the publisher if there's no name listed.

You can add your corrections to this PR too since we still need to make updates.

**Comment by jennfrye** [comment]
That was easier than I thought! I corrected the issues you identified and both `se lint` and `se build --check-only` come back completely clean (again, excepting those errors I always get). 

No translator was listed in the source scans I used, so I attributed the annotations to the publisher (J. M. Dent and Company) as you recommended.

**Comment by acabal** [comment]
Great, thanks. In the future, please use numbers for endnotes, not stars. This is easy enough to fix using `se renumber-endnotes` so I'll just do it on my end.

**Comment by jennfrye** [comment]
> Great, thanks. In the future, please use numbers for endnotes, not stars. This is easy enough to fix using `se renumber-endnotes` so I'll just do it on my end.

Will do! Thank you!

**Pull request merged**
