### PR TITLE
Typo correction

### PR DESCRIPTION
**Pull request by jennfrye**

### CODE REVIEW

**Comment by acabal** [comment]
Thanks!

**Comment by jennfrye** [comment]
> Thanks!

FYI, I am working on adding in public domain translations and I'm getting errors when running se lint and se build --check-only. This is the first time I'm running either on any version of Villette, and since I haven't changed the lines that are cited in the error message, I think the errors must exist in the current version. 

I've been unable to figure out the problem as everything looks right to me. 

The errors are:

When running se lint: Error  Couldn’t parse XML in /tmp/tmpbcqrj60c/charlotte-bronte_villette-newest/epub/text/chapter-38.xhtml. Exception:
Opening and ending tag mismatch: section line 9 and span, line 49, column 544 (<string>, line 49)

When running se build --check-only: Error  Couldn’t parse XML in /home/jennfr/charlotte-bronte_villette-newest/src/epub/text/chapter-9.xhtml. Exception:
Opening and ending tag mismatch: span line 43 and i, line 43, column 687 (<string>, line 43)

**Comment by acabal** [comment]
Not sure, both tools work fine for me. You can open the files in question to inspect the XHTML and see where the tags ended up getting mismatched.

**Comment by jennfrye** [comment]
> Not sure, both tools work fine for me. You can open the files in question to inspect the XHTML and see where the tags ended up getting mismatched.

Thank you so much for checking! No idea what went wrong but starting fresh and copying everything over did the trick—not something I would have tried otherwise.

**Pull request merged**
